spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file://C:\Users\eassissilva\workspace\microservices\git-localconfig-repo

server:
  port: 8888



